config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'triangles/index'
  mount Sidekiq::Web => '/sidekiq'
  resources :markets
  resources :margins, only: [:index]
  resources :triangles, only: [:index]
  resources :rates, only: [:index]
  root "markets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  validates :slug, :ticker, presence: true
  validates :slug, :ticker, uniqueness: true
end

# == Schema Information
#
# Table name: assets
#
#  id         :bigint           not null, primary key
#  name       :string
#  slug       :string
#  ticker     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/margin.rb
class Margin < ApplicationRecord
  belongs_to :base, class_name: "Pair"
  belongs_to :quote, class_name: "Pair"

  def reverse_margin
    Margin.where(base: quote, quote: base).take
  end
end

# == Schema Information
#
# Table name: margins
#
#  id         :bigint           not null, primary key
#  decimal    :decimal(20, 10)  default(0.0), not null
#  margin     :decimal(20, 10)  default(0.0), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  base_id    :integer          not null
#  quote_id   :integer          not null
#

app/models/market.rb
class Market < ApplicationRecord
  has_many :pairs, dependent: :destroy
end

# == Schema Information
#
# Table name: markets
#
#  id         :bigint           not null, primary key
#  name       :string
#  slug       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/pair.rb
class Pair < ApplicationRecord
  belongs_to :base, class_name: "Asset"
  belongs_to :quote, class_name: "Asset"
  belongs_to :market

  scope :with_rate, -> { where.not(rate: 0) }

  def reverse_pairs
    Pair.where(base: quote, quote: base)
  end
end

# == Schema Information
#
# Table name: pairs
#
#  id         :bigint           not null, primary key
#  name       :string
#  price_btc  :decimal(20, 10)  default(0.0), not null
#  rate       :decimal(20, 10)  default(0.0), not null
#  slug       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  base_id    :integer          not null
#  market_id  :integer
#  quote_id   :integer          not null
#

app/models/triangle.rb
class Triangle < ApplicationRecord
  belongs_to :pair_a, class_name: "Pair"
  belongs_to :pair_b, class_name: "Pair"
  belongs_to :pair_c, class_name: "Pair"
end

# == Schema Information
#
# Table name: triangles
#
#  id         :bigint           not null, primary key
#  rate       :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  pair_a_id  :bigint           not null
#  pair_b_id  :bigint           not null
#  pair_c_id  :bigint           not null
#
# Indexes
#
#  index_triangles_on_pair_a_id  (pair_a_id)
#  index_triangles_on_pair_b_id  (pair_b_id)
#  index_triangles_on_pair_c_id  (pair_c_id)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/margins_controller.rb
class MarginsController < ApplicationController
  def index
    @margins = Margin.includes(base: [:base,:quote], quote: [:base,:quote])
      .where("margin > 0").order(margin: :desc).limit(100)
      .page(params[:page]).per(20)
  end
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :set_market, only: [:edit, :upadte, :destroy]
  def index
    @markets = Market.all.page(params[:page]).per(20)
  end

  def new
    @market = Market.new
  end

  def edit
  end

  def create
    @market = Market.new(market_params)

    if @market.save
      redirect_to markets_path
    else
      render :new
    end
  end

  def update

  end

  def destroy
  end

  private

  def market_params
    params.require(:market).permit(:name, :slug)
  end
end

app/controllers/pairs_controller.rb
class PairsController < ApplicationController
  def index

  end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  def index
    @markets = Market.includes(:pairs).all
  end
end

app/controllers/triangles_controller.rb
class TrianglesController < ApplicationController
  def index
    @triangles = Triangle.where("rate < ?", 26).includes([:pair_a, :pair_b, :pair_c])
      .order(rate: :desc).page(params[:page]).per(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/helpers/pairs_helper.rb
module PairsHelper
end

app/views/home/index.haml
%h1 Here we will show a chart

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title cryptrage
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/navbar'
    %main.container-fluid
      = yield

app/views/margins/index.haml
%h4 Margin of value for the same pairs in different markets
%br
%div.market-tables.margin-table
  %table.table.table-striped.table-borderless.table-hover.table-responsive.table-sm
    %thead.table-primary
      %tr.table-primary
        %th
        %th{colspan: 3} Base market
        %th
        %th{colspan: 3} Quote market
        %th{:scope => "col"} Profit
      %tr.table-dark
        %th{:scope => "col"} #
        %th{:scope => "col"} Name
        %th{:scope => "col"} Base
        %th{:scope => "col"} Quote
        %th{:scope => "col-xs"}
        %th{:scope => "col"} Name
        %th{:scope => "col"} Base
        %th{:scope => "col"} Quote
        %th{:scope => "col"} %
    %tbody.text-small
      - @margins.each_with_index do |margin, i|
        %tr{id: "row#{margin.id}"}
          %td= i + 1
          %td= margin.base.market.name
          %td= margin.base.base.ticker + " - " + margin.base.base.name
          %td= margin.base.quote.ticker + " - " + margin.base.quote.name
          %td
            %i.fas.fa-arrow-right
          %td= margin.quote.market.name
          %td= margin.quote.base.ticker + " - " + margin.quote.base.name
          %td= margin.quote.quote.ticker + " - " + margin.quote.quote.name
          %td.rate.bg-dark.text-light= margin.margin.to_s + " %"

  = paginate @margins

app/views/margins/index.html.haml
%h2 Top 100 crypto margin opportunities
%br
%div.market-tables.margin-table
  %table.table.table-striped.table-borderless.table-hover
    %thead.table-primary
      %tr.table-primary
        %th
        %th{colspan: 3} Base market
        %th
        %th{colspan: 3} Quote market
        %th{:scope => "col"} Percentage
      %tr.table-dark
        %th{:scope => "col"} #
        %th{:scope => "col"} Name
        %th{:scope => "col"} Base
        %th{:scope => "col"} Quote
        %th{:scope => "col-xs"}
        %th{:scope => "col"} Name
        %th{:scope => "col"} Base
        %th{:scope => "col"} Quote
        %th{:scope => "col"} %
    %tbody.text-small
      - @margins.each_with_index do |margin, i|
        %tr{id: "row#{margin.id}"}
          %td= i + 1
          %td= margin.base.market.name
          %td= margin.base.base.ticker + " - " + margin.base.base.name
          %td= margin.base.quote.ticker + " - " + margin.base.quote.name
          %td
            %i.fas.fa-arrow-right
          %td= margin.quote.market.name
          %td= margin.quote.base.ticker + " - " + margin.quote.base.name
          %td= margin.quote.quote.ticker + " - " + margin.quote.quote.name
          %td.rate= margin.margin.to_s + " %"

app/views/markets/_form.haml
= form_for @market, class: 'form-control' do |f|
  .form-group
    = f.label :name, class: "form-label"
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :slug, class: "form-label"
    = f.text_field :slug, class: "form-control"
  .mt-3
    = f.submit 'Submit', class: "btn btn-primary"

app/views/markets/index.html.haml
.col-md-12
  %table.table.table-striped.table-borderless.table-hover
    %thead.table-primary
      %tr
        %th{:scope => "col"} Market
        %th{:scope => "col"} Pairs
        %th.col-md-1{:scope => "col-md-1"} Actions
      %tbody
        - @markets.each do |market|
          %tr{id: "row#{market.id}"}
            %td
              .d-inline= market.name
              .d-inline.small.text-secondary= market.slug
            %td= market.pairs.count
            %td.col-md-1
              = link_to market, method: :delete, data: { confirm: 'Are you sure?' } do
                %i.fas.fa-trash.text-danger

  = paginate @markets

app/views/markets/new.haml
%h1 New market
= render "form"

app/views/pairs/index.html.haml
.grid-tables
  - @pairs.each do |pair|
    %div
      %table.table.table-striped.table-light.table-borderless.table-hover
        %thead.table-primary
          %tr
            %th.h5{colspan: 3}= pair.name
          %tr.table-dark
            %th{:scope => "col"} Market
            %th{:scope => "col"} Rate
        %tbody
          - pair.markets.each do |market|
            %tr
              %td{:scope => "row"}= pair.base.ticker
              %td= pair.quote.ticker

app/views/rates/index.haml
.market-tables.grid-tables
  - @markets.each do |market|
    %div
      %table.table.table-striped.table-borderless.table-hover
        %thead.table-primary
          %tr
            %th.h5{colspan: 3}= market.name
          %tr.table-dark
            %th{:scope => "col"} Base
            %th{:scope => "col"} Quote
            %th{:scope => "col"} Rate
        %tbody
          - market.pairs.includes(:base, :quote).with_rate.each do |pair|
            %tr{id: "row#{pair.id}"}
              %td{:scope => "row"}= pair.base.ticker
              %td= pair.quote.ticker
              %td.rate= pair.rate.to_s

app/views/shared/_navbar.haml
%nav.navbar.navbar-expand-md.navbar-light.bg-light.fixed-top
  .container-fluid
    = link_to root_path, class: 'navbar-brand' do
      cryptrage
      %i.fas.fa-project-diagram

    %button.navbar-toggler{"aria-controls" => "menu", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#menu", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #menu.collapse.navbar-collapse
      %ul.navbar-nav.justify-content-between.me-auto.mb-2.mb-md-0
        %li.nav-item.dropdown{class: "#{'active' if params[:controller] == 'markets'}"}
          %a#dropdown01.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#"} Markets
          %ul.dropdown-menu{"aria-labelledby" => "dropdown01"}
            %li
              = link_to "List", markets_path, class: 'dropdown-item'
            %li
              = link_to "Create", new_market_path, class: 'dropdown-item'

        %li.nav-item{class: "#{'active' if params[:controller] == 'margins'}"}
          = link_to "Reverse pair", margins_path, class: 'nav-link'
        %li.nav-item{class: "#{'active' if params[:controller] == 'triangles'}"}
          = link_to "Triangular", triangles_path, class: 'nav-link'
      -#
        %li.nav-item{class: "#{'active' if params[:controller] == ''}"}
          = link_to "Insane", markets_path, class: 'nav-link'

app/views/triangles/index.haml
%h4 Opportunities for profitable triangular arbitrage
%br
%div.market-tables.margin-table
  %table.table.table-striped.table-borderless.table-hover.table-responsive.table-sm
    %thead.table-primary
      %tr.table-primary
        %th
        %th{colspan: 3} Pair A
        %th
        %th{colspan: 3} Pair B
        %th
        %th{colspan: 3} Pair C
        %th{:scope => "col"} Profit
      %tr.table-dark
        %th{:scope => "col"} #
        %th{:scope => "col"} Market
        %th{:scope => "col"} Base
        %th{:scope => "col"} Quote
        %th{:scope => "col-xs"}
        %th{:scope => "col"} Market
        %th{:scope => "col"} Base
        %th{:scope => "col"} Quote
        %th{:scope => "col-xs"}
        %th{:scope => "col"} Market
        %th{:scope => "col"} Base
        %th{:scope => "col"} Quote
        %th{:scope => "col"} %
    %tbody.text-small
      - @triangles.each_with_index do |triangle, i|
        %tr{id: "row#{triangle.id}"}
          %td= i + 1
          %td.text-secondary= triangle.pair_a.market.name
          %td= triangle.pair_a.base.ticker + " - " + triangle.pair_a.base.name
          %td= triangle.pair_a.quote.ticker + " - " + triangle.pair_a.quote.name
          %td
            %i.fas.fa-arrow-right
          %td.text-secondary= triangle.pair_b.market.name
          %td= triangle.pair_b.base.ticker + " - " + triangle.pair_b.base.name
          %td= triangle.pair_b.quote.ticker + " - " + triangle.pair_b.quote.name
          %td
            %i.fas.fa-arrow-right
          %td.text-secondary= triangle.pair_c.market.name
          %td= triangle.pair_c.base.ticker + " - " + triangle.pair_c.base.name
          %td= triangle.pair_c.quote.ticker + " - " + triangle.pair_c.quote.name
          %td.rate.bg-dark.text-light= triangle.rate.to_s + " %"

  = paginate @triangles, window: 20